apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: kafka-bridge # Change here to change the resource name
  namespace: kafka # Change here if it is another namespace
spec:
  bootstrapServers: 'kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092' # Change here to match the `Kafka Bootstrap Servers` address
  http:
    port: 8080 # Change here to change the port
  replicas: 1